# Docker Compose file for Symfony staging environment deployment
services:
  ###> symfony/staging ###
  app_staging:
    image: ${DOCKER_IMAGE}:latest
    container_name: ${CONTAINER_NAME_STAGING}
    restart: always
    environment:
      APP_ENV: staging
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      MAILER_DSN: ${MAILER_DSN}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    working_dir: /app
    ports:
      - "9001:80"
    depends_on:
      - database_staging
  ###< symfony/staging ###

  ###> symfony/database_staging ###
  database_staging:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: ecoride_db_staging
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_STAGING}
      POSTGRES_USER: ${POSTGRES_USER_STAGING}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_STAGING}
    volumes:
      - database_staging_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB_STAGING}", "-U", "${POSTGRES_USER_STAGING}"]
      timeout: 5s
      retries: 5
      start_period: 10s
  ###< symfony/database_staging ###

volumes:
  database_staging_data:
